

const members = [

  {
     name: "Sonakshi Arora",
     position: "Convener ",
     team: "ECcc",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/427f1314-bfeb-4b52-8e3f-9bf25d7d359a_Sonakshi+Arora+-+Chairperson%281%29.jpg?auto=compress,format",
   },
   {
     name: "Sriansh Raj",
     position: "Convener",
     team: "ECcc",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/5c96bb42-fab5-47ec-9d8f-6706468145dc_Sriansh+Raj_head+of+Promotions.png?auto=compress,format",
   },
   {
     name: "Yuvraj Vasudeva",
     position: "Convener",
     team: "ECcc",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/4bdf0e30-8fbc-4ff3-a1ab-613eedb21db2_WhatsApp+Image+2023-08-18+at+6.44.06+PM.jpeg?auto=compress,format",
   },
   {
     name: "Abhimanyu Bhasin",
     position: "Director",
     team: "ECcc",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/7117df8d-d3be-4461-82f5-a6e7d3dca21a_Human+Resource+director+.JPG?auto=compress,format",
   },
   {
     name: "Aditya Pandey",
     position: "Director",
     team: "ECcc",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/cb2112fd-a2bf-4a2b-9999-3a3dc3f7402e_Aditya+Pandey_Joint+Head+of+Promotions.jpg?auto=compress,format",
   },
   {
     name: "Anish Ubriani",
     position: "Director",
     team: "ECcc",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/bd716baf-e44f-43fa-818e-5849fbf5b13c_Anish+Ubriani.jpg?auto=compress,format",
   },
   {
     name: "Anoushka Goyal",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f809b035-ebef-4d34-81b7-6a46693f214f_Anoushka+Goyal.JPG?auto=compress,format",
   },
   {
     name: "Atul Raj Sharma",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/59f97e47-ff20-4c66-8306-90568ab88cbb_Atul+Raj+Sharma_+Head+of+Programs_.jpg?auto=compress,format",
   },
   {
     name: "Avanya Sagar",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/64567779-1509-47c1-b7a0-b764b8fa1e6a_Avanya+Sagar-+Treasurer%281%29.png?auto=compress,format",
   },
   {
     name: "Dev Agrawal",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/29ff6235-c35d-4a13-b828-9d01c9893e6b_Dev+Agrawal.jpg?auto=compress,format",
   },
   {
     name: "Divya Srivastva",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/e42f1e1d-4ccd-43cf-aaff-425708211e16_Divya+Joint+Head+of+Programs.png?auto=compress,format",
   },
   {
     name: "Khushi Ganatra",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/435bfcff-aebb-41a3-9ab1-8999d4ce25c2_Khushi_Ganatra.jpg?auto=compress,format",
   },
   {
     name: "Kshiti Malla",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f3215139-b9ab-460e-8fbf-20d1cf1b1102_Kshiti+Malla+-+Vice+Chair.jpeg?auto=compress,format",
   },
   {
     name: "Rajveer Sanghavi",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/7cce8312-9693-4a46-bc13-0a69ca5e9fd8_Rajveer_Sanghavi_SeniorProgramsCoordinator.png?auto=compress,format",
   },
   {
     name: "Rishabh Bassi",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/9b36e700-6aa5-433c-9572-e8092e07610e_Rishabhbass+Joint+head+of+graphic+design.jpeg?auto=compress,format",
   },
   {
     name: "Saloni Agrawal",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3481f165-c4fd-4e4e-ba79-996fa32b8832_Saloni+Agrawal+-+Managing+Director.jpg?auto=compress,format",
   },
   {
     name: "Shekhar Pilania",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/4cc855d9-00c2-4ff1-aee6-88aeaa717ad5_Shekhar_senior+program+coordinator.jpg?auto=compress,format",
   },
   {
     name: "Vanshika S Andotra",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3dcda231-7140-4211-87e1-5c516f19da41_Vanshika_GenSec.jpg?auto=compress,format",
   },
   {
     name: "Vidit Parashar",
     position: "Director",
     team: "EC",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/626e8cbc-a750-439a-a21f-6a6123f14ab3_IMG_20230612_002853.jpg?auto=compress,format",
   },
   
   {
     name: "Aaranay Aadi",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/92366ef1-f2d6-4ac4-b1b5-1403443bda40_Aaranay+Aadi.jpg?auto=compress,format",
   },
   {
     name: "Aish Sinha",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f57562d6-c63c-4bf1-bedf-48829def71a3_AISH+SINHA.jpeg?auto=compress,format",
   },
   {
     name: "Anushka Soni",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3a7873e6-2421-40a5-8b0b-13c8baa3143a_WhatsApp+Image+2023-07-13+at+4.59.18+PM.jpeg?auto=compress,format",
   },
   {
     name: "Arham Jain",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/671879e4-2cde-4077-aea6-abcd5afed81c_Arham+Jain.jpg?auto=compress,format",
   },
   {
     name: "Ayana Takshak",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/692a3910-0b46-46fe-8e75-33afb186d14e_Ayana+takshak.jpeg?auto=compress,format",
   },
   {
     name: "Het Valera",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3ca51db2-3a30-4020-bd08-01c307d20409_Het_Valera.jpg?auto=compress,format",
   },
   {
     name: "Ishank Bansal",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Suhani Talreja",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/db15f804-f556-47b1-b52d-17434da2e6c2_Suhani+Talreja.jpg?auto=compress,format",
   },
   {
     name: "Jiya Gupta",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/2eef1020-a4b0-46b7-a328-d3e4c2989e3c_IMG_3025+-+Jiya+gupta.jpeg?auto=compress,format",
   },
   {
     name: "Karan Kapoor",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/e18134c6-fb64-4659-8bc3-df3224374bc6_Karan+Kapoor_.jpg?auto=compress,format",
   },
   {
     name: "Kashish Bhasin",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/72c12942-2c2c-489a-9720-9c3798178ee0_KASHISH+BHASIN.jpg?auto=compress,format",
   },
   {
     name: "Naad Dantale",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Pavni Jain",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/8156911d-9235-42e9-bde4-999c482749ab_Pavni+Jain.jpg?auto=compress,format",
   },
   {
     name: "Risha Uppal",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/375f55b8-2427-4655-88dc-07d54ecd6b60_Risha+Uppal.jpg?auto=compress,format",
   },
   {
     name: "Samyak Jain",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/1142e185-7cee-4721-8157-88783727e85a_SAMYAK+JAIN.jpg?auto=compress,format",
   },
   {
     name: "Vivin Pathak",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/bbb28b0f-4a6d-4de2-a654-8c8f76c9351f_vivan.png?auto=compress,format",
   },
   {
     name: "Suhani Talreja",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/6f20e76c-4224-4a4f-92db-7b42a716449d_Aanchal+Mittal_Head+of+corporate+affairs.jpg?auto=compress,format",
   },
   {
     name: "Saumya Gupta",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/191861e0-8670-48ed-a149-f8a2f4dd89f6_Saumya+Gupta-Senior+Coordinator%28Programs%29.jpg?auto=compress,format",
   },
   {
     name: "Shreja Shekhar",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/bf24c4c2-b45f-43b1-a728-b43459f0bf79_Shreja+-+Head+of+Promotions.jpg?auto=compress,format",
   },
   {
     name: "Shrivatsa Trivedi",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/db9beccb-e094-4358-bec4-71c01f942352_Shrivatsa+Trivedi+_.jpg?auto=compress,format",
   },
   {
     name: "Shubham Kukreti",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/2b1001df-1e90-4f6e-a50f-4e64dec7ea5f_Shubham+Kukreti_.jpg?auto=compress,format",
   },
   {
     name: "Supriya Srivastva",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/5fdf1bb7-7e68-4326-b98b-6794660300e8_20230704_143718439+-+Supriya+Srivastava.jpg?auto=compress,format",
   },
   {
     name: "Utkarsh Shukla",
     position: "",
     team: "CCevents",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/53863383-fd04-4283-8d9e-0b2615260fe1_Utkarsh+Shukla.jpg?auto=compress,format",
   },
   
   
   {
     name: "Aditi Banga",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/26d0ca9f-b9d4-4215-90c8-621a4baabeb0_Aditi+Banga.jpeg?auto=compress,format",
   },
   {
     name: "Madhurima Roy",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f61e8087-6410-43bc-b3d2-e4ee67b605cc_Madhurima+Roy.jpeg?auto=compress,format",
   },
   {
     name: "Rishita Jain",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b2b52f86-3afe-42d7-8a09-d69825c604d0_Rishita+Jain.webp?auto=compress,format",
   },
   {
     name: "Aradhya Khandelwal",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/03792ed0-8bf0-49ea-a84e-b736f4f01b36_IMG_20220911_010603_124+-+Aradhya+Khandelwal.jpg?auto=compress,format",
     
   },
   {
     name: "Naysa Saini",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f36ebbab-2e0d-4ad2-a9e7-54fe75cdfbab_Naysa+Saini.jpg?auto=compress,format",
   },
   {
     name: "Vanshika Khanna",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/11c30ad1-e252-4a30-95d0-b3193b039d41_Vanshika+Khanna.jpg?auto=compress,format",
   },
   {
     name: "Kaushal Shukla",
     position: "",
     team: "CCcurations",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Aakash Mukharjee",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/2afe2089-f995-4180-b308-5eb80deb4f9a_IMG-20221211-WA0029-01+-+Akash+Mukherjee.jpg?auto=compress,format",
   },
   {
     name: "Devyani  Ghildiyal",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Nidhi Verma",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/c10fd71c-532f-48a9-9a7d-b9199a228115_Nidhi+Verma.jpg?auto=compress,format",
   },
   {
     name: "Aashi Sharma",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/7746d9e2-b906-4bce-a574-4230017c0e55_Aashi+Sharma.jpg?auto=compress,format",
   },
   {
     name: "Himalaya Sharma",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/7121419e-8587-48e7-9db4-29232ac9a9ad_HIMALAYA+SHARMA.jpg?auto=compress,format",
   },
   {
     name: "Pujan Modha",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3dda7e22-a017-4f7d-bffd-e31d75981173_pujan+modha.JPG?auto=compress,format",
   },
   {
     name: "Anjali Tyagi",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/a9e84762-e690-4895-b3c4-83d8b23ef5d2_Anjali+Tyagi.jpg?auto=compress,format",
   },
   {
     name: "Kunal Kumar",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/7c720e8b-00d6-47f4-be50-afb437c52456_Kunal+Kumar.jpg?auto=compress,format",
   },
   {
     name: "Ranojit Palit",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/ce2688f3-c930-439b-b48a-ba09f5c0ca59_Ranojit+Palit+.jpeg?auto=compress,format",
   },
   {
     name: "Ansh Tandon",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Lavanya Agrawal",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/aed95d28-2998-4188-83e8-6578d6537523_Lavanya+Agrawal.webp?auto=compress,format",
   },
   {
     name: "Saniya Wadhwani",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/18fe92d4-f459-4f3b-bb85-751964929804_Saniya+Wadhwani+.jpg?auto=compress,format",
   },
   {
     name: "Arhaan Abdullah",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/004472ec-d472-47d5-aad2-862fb081847b_Arhaan+Abdullah+.jpeg?auto=compress,format",
   },
   {
     name: "Lipika Dudeja",
     position: "",
     team: "CCmarketing",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/4eea7f4e-040a-4ba8-9ec6-46f7567335e2_Lipika+Dudeja.jpg?auto=compress,format",
   },
   {
     name: "Kartik Taneja",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Satvik Agrawal",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/ca87d28a-6237-4754-89c3-93ba9224a82d_IMG-20230320-WA0003+-+Satvik+Agarwal.jpg?auto=compress,format",
   },
   {
     name: "Atharv Thakle",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/333252b7-9aa5-4927-8b33-50502704a77a_IMG_20230613_225707+-+Atharv+Thakle.jpg?auto=compress,format",
   },
   {
     name: "Mohit Hingorani",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/8add325c-46f6-4bcd-b57d-51bc1dd7aff2_Mohit+Hingorani+-+Mohit.jpg?auto=compress,format",
   },
   {
     name: "Tanishq Khurana",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/5e722425-509c-4797-baff-0e49ea368c9b_IMG_20221028_143820+-+Tanishq+Khurana.jpg?auto=compress,format",
   },
   {
     name: "Armaan Deep",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Krishnav Gupta",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/103847ee-8cde-491e-a643-841dc30cad7e_krishnav+gupta.jpg?auto=compress,format",
   },
   {
     name: "Sanyam Modi",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/41a1a33c-b559-43f9-b782-360578d4aad2_sanyam+modi.jpg?auto=compress,format",
   },
   {
     name: "Ayush Gupta",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Paksh Raheja",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/1b49eabf-6a89-403c-9f44-ea8dfdb1d716_Paksh+Raheja_.jpg?auto=compress,format",
   },
   {
     name: "Vansh Jaggi",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Deepak Chauhan",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Parv Aggarwal",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b6d5ebfd-290d-4565-8edc-8915219fbb1a_2023-08-13+18_25_49-Parv_Aggarwal.heic+%E2%80%8E-+Photos.png?auto=compress,format",
   },
   {
     name: "Yash Prasad",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3742f70f-1151-4ebd-ad89-93a06ea28191_Yash+Prasad.jpeg?auto=compress,format",
   },
   {
     name: "Diya Goyal",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/092869e8-77a5-49ac-971b-f6252fecc4b3_Diya+Goyal.jpg?auto=compress,format",
   },
   {
     name: "Sai Voona",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Yashvi Neema",
     position: "",
     team: "CClogistics",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/56101184-d006-4c50-9978-3cfaa80f0ac3_Yashvi+Neema.jpg?auto=compress,format",
   },
   {
     name: "Aayushi Gupta",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/be5ea0f8-ad25-426c-8d24-8336c149c016_Aayushi+Gupta+-+Senior+Coordinator+%28Editorial%29.jpg?auto=compress,format",
   },
   {
     name: "Rohan Raj",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/d840f0fd-fe13-4468-ae98-6fbe95e36529_Rohan+Raj.jpg?auto=compress,format",
   },
   {
     name: "Shreshth Goyal",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/94caf447-e6b2-4f63-82d0-217bb90092ee_Shreshth+Goyal.jpeg?auto=compress,format",
   },
   {
     name: "Anushka Pawar",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/096aa7d7-c37b-48ff-83b9-d3e66a355f31_Anushka+Pawar.jpg?auto=compress,format",
   },
   {
     name: "Rutu Bhandari",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Smriti",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/81b01667-8847-41e5-88d5-3fea43401b00_Smriti.jpg?auto=compress,format",
   },
   {
     name: "Medini",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b51d01d6-0857-48c7-ab0f-05b9f5c82e7d_medini+budhalakoti.jpeg?auto=compress,format",
   },
   {
     name: "Sehul Singh",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Vaidehi Agarwal",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/367e2e4a-efae-466d-a3d8-152e2c2910cd_Vaidehi+Agarwal_.jpg?auto=compress,format",
   },
   {
     name: "Nishant Thottarah",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Diya Thakur",
     position: "",
     team: "CCcontent",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/8a3deb1c-1abb-459a-bf90-82b6a1e876cf_Diya+Thakur.jpg?auto=compress,format",
   },
  
   {
     name: "Prashant Saraswat",
     position: "",
     team: "CCfinance",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Aarya Pareek",
     position: "",
     team: "CCfinance",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/1a19a7f2-174e-47ea-b341-ce35a559a084_Aarya+Pareek.jpeg?auto=compress,format",
   },
   {
     name: "Rashi Sharma",
     position: "",
     team: "CCfinance",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/457d1ba8-4f15-40d2-9457-91f7e68ec410_Rashi+Sharma_.jpg?auto=compress,format",
   },
   {
     name: "Suhani Valecha",
     position: "",
     team: "CCfinance",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f080e4a7-c38d-42d5-a56a-0ec921f7c7db_Suhani+Valecha-Head+of+Corporate+affairs.JPG?auto=compress,format",
   },
   {
     name: "Agam Arora",
     position: "",
     team: "CCfinance",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Rushil Misra",
     position: "",
     team: "CCfinance",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/81aefa1c-3385-42c7-9c28-4877963e85ba_Mohammad+ruseel.jpg?auto=compress,format",
   },
  
   {
     name: "Ananya Raman",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/4b05ad02-4b32-4118-88d5-15f62ae5ba25_Ananya+Raman+.jpeg?auto=compress,format",
   },
   {
     name: "Mithilesh S Mudaliar",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/c41a13ef-8d64-4f5a-8a4c-3afacace0024_Mithilesh+Mudaliar_.jpg?auto=compress,format",
   },
   {
     name: "Pratham Shrivastva",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Avni Ahuja",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/6a372ae0-c490-46c7-97a6-61fd96163b54_IMG_2656+-+Avni+Ahuja.jpeg?auto=compress,format",
   },
   {
     name: "Ankit Singh",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/bff91401-ee0c-4b8b-a546-67282f9ab859_Ankit-Singh.jpg?auto=compress,format",
   },
   {
     name: "Mohini",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/c8218757-b33d-4137-b943-1b1e9aafa0bf_Mohini+Vashisth.jpg?auto=compress,format",
   },
   {
     name: "Rohan Arora",
     position: "",
     team: "CChospitality",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/cadf1d64-c9d5-4789-a3a1-b5674c4c9cc5_Rohan+Arora.jpg?auto=compress,format",
   },
   {
     name: "Aastha Rawat",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/0e099793-4176-4020-90ed-51c2819884b1_AASTHA+RAWAT.jpg?auto=compress,format",
   },
   {
     name: "Aahana Verma",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/1dcf9450-64ec-4569-bdc9-cb04c3dec27f_IMG-20221216-WA0034+-+Ahaana+Verma.jpg?auto=compress,format",
   },
   {
     name: "Gouri Sharma",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f6cfd31c-8a90-4561-9baa-d041089103c7_Gouri+Sharma-+Joint+Head+of+Graphic+Design.jpg?auto=compress,format",
   },
   {
     name: "Jatan Prag Bhatt",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/8eac9e73-28e6-4b1e-a992-a162ab5afa48_20230623_195549+-+Jatan+bhatt.jpg?auto=compress,format",
   },
   {
     name: "Shreya Saighal",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Kanisha Bansal",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/156ccbb3-3f4a-49bd-9c5d-af5bf88e070f_Kanisha_cc_reveal+-+Kanisha.jpeg?auto=compress,format",
   },
   {
     name: "Siddharth Chandra",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/e3103ae4-50ed-45cb-9faf-0c9b4153dae3_WhatsApp+Image+2023-07-14+at+10.27.04+AM.jpeg?auto=compress,format",
   },
   {
     name: "Nalin Datta",
     position: "",
     team: "CCgraphicdesign",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/4f3d7925-ce61-4428-aa82-56dca0cf10f3_me+-+Nalin.jpg?auto=compress,format",
   },
   {
     name: " Bhavya Arora",
     position: "",
     team: "CCwebdev",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/5606e275-2efc-479c-af1e-eb30071673c4_WhatsApp+Image+2023-07-14+at+10.04.27+AM.jpeg?auto=compress,format",
   },
   {
     name: "Rishi Joshi",
     position: "",
     team: "CCwebdev",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/a08cac1d-9cc1-4bf6-8ccc-9181760b3b4c_RISHI+JOSHI.jpg?auto=compress,format",
   },
   {
     name: "Kushagra Saxena",
     position: "",
     team: "CCwebdev",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/2cd2e098-69a4-4fe7-9642-d6fa066a70a2_IMG_20230409_020820+-+kushagra+saxena.jpg?auto=compress,format",
   },
   {
     name: "Aayush Katyal",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/a6f5bed5-1c71-43e4-8a80-30736abbcfab_ayush+katyal.jpeg?auto=compress,format",
   },
   {
     name: "Mahak Lashkray",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/cd6760b8-1bfe-4d6e-9ec7-cd9b885c1ce9_Mahak+Lashkary.jpg?auto=compress,format",
   },
   {
     name: "Saransh Suri",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/0df9908b-a8aa-4537-ab94-be82c7bed4e4_saransh+suri.jpg?auto=compress,format",
   },
   {
     name: "Shivangi Singh",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/84882cb9-9edf-47dc-8ae7-459dae2e1982_Shivangi+Singh.jpg?auto=compress,format",
   },
   {
     name: "Pranav Bharadwaj",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f13b0974-cddb-4d7a-8322-4e54f7372a46_image+for+genesis+-+Pranav+Bhardwaj.jpg?auto=compress,format",
   },
   {
     name: "Arunabha",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/974f7aef-d7e6-4a0e-a7dd-bfa082b7a4fb_Arunabha_Mukhopadhyay.jpg?auto=compress,format",
   },
   {
     name: "Devansh Bansal",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/be2e72fc-7a5c-4ba3-8fd8-39c77925b1e6_Devansh+Bansal.jpg?auto=compress,format",
   },
   
   {
     name: "Rishabh Shetty",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/c8fec354-1afc-418a-95f4-fb43c0125ff4_Rishabh+Shetty+-+Senior+Coordinator+%28Programs%29.jpg?auto=compress,format",
   },
   {
     name: "Vikramaditya Hiran",
     position: "",
     team: "CCflyingsquad",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/6fdc2708-e7d5-4d5e-9be3-95176359e6ca_Vikramaditya+Hiran.jpg?auto=compress,format",
   },
   {
     name: "Atharv Thakle",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/333252b7-9aa5-4927-8b33-50502704a77a_IMG_20230613_225707+-+Atharv+Thakle.jpg?auto=compress,format",
   },
   {
     name: "Kanishka Choudhry",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Manushree Pande",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/0032fdd8-bd56-4541-80e9-068d51aeef8a_Manushree+Pande-+Senior+Coordinator+%28Graphic+Design%29.jpg?auto=compress,format",
   },
   {
     name: "Ayana Takshak",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/692a3910-0b46-46fe-8e75-33afb186d14e_Ayana+takshak.jpeg?auto=compress,format",
   },
   {
     name: "Kasvi Soni",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/ad4aaabf-fec4-497c-8e48-67246a0d7c55_Kasvii.jpeg?auto=compress,format",
   },
   {
     name: "Suryansh Jain",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/fd834d4b-9984-42d7-bac2-2a4470ab5100_Suryansh_jain.jpeg?auto=compress,format",
   },
   {
     name: "Gun Goyal",
     position: "",
     team: "CCcrafts",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/9cbfc9cc-8af3-4021-a57b-9a7d781eb21e_WhatsApp+Image+2023-07-14+at+9.44.00+AM.jpeg?auto=compress,format",
   },
   {
     name: "Amit Patro",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Aryan Jain",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/f3903453-75e3-47b1-8b78-eaa3c11c334a_Aryan+Jain.jpg?auto=compress,format",
   },
   {
     name: "Aryan Jhamnani",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/90f3b094-d2eb-41ba-983f-4f1da680a5f6_Aryan_Jhamnani_229309143.jpg?auto=compress,format",
   },
   {
     name: "Aslesh Patra",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Janhavi Rewatkar",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/d78ff913-102f-4e47-994b-39ade6bb639a_janhavi+rewatkar+.jpg?auto=compress,format",
   },
   {
     name: "Kanav Bhalla",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/09004d60-d853-48f2-b031-5d1c6b5675d6_Kanav+Bhalla.jpg?auto=compress,format",
   },
   {
     name: "Medini Budhalakoti",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b51d01d6-0857-48c7-ab0f-05b9f5c82e7d_medini+budhalakoti.jpeg?auto=compress,format",
   },
   {
     name: "Mrigakshi Dev",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/01d1bab4-43d7-49a0-9d37-e64ae705834a_MRIGAKSHI+DEV.jpeg?auto=compress,format",
   },
   {
     name: "Navya Tekriwal",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Navyaa Kabra",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b16c1d59-f046-4e52-a205-ca5c27c5f60f_Navyaa+Kabra.jpg?auto=compress,format",
   },
   {
     name: "Nitya Shukla",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/979ffd2f-d657-4c27-a367-d1dfb5796bcb_nitya+shukla.jpg?auto=compress,format",
   },
   {
     name: "Pratincha Singh",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/82fe8070-a979-4772-9c24-47871f2b3d10_Photo1+-+Pratincha+Singh.jpg?auto=compress,format",
   },
   {
     name: "Prerit Verma",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/cbf3d320-68b4-488a-a151-3923380552d1_Prerit+Verma.jpeg?auto=compress,format",
   },
   {
     name: "Ritvik Singh",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/eb1f300d-16d5-46b7-a6bf-f23ddbfd7e28_Ritvik+Singh.jpg?auto=compress,format",
   },
   {
     name: "Suryansh Jain",
     position: "",
     team: "CCmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/fd834d4b-9984-42d7-bac2-2a4470ab5100_Suryansh_jain.jpeg?auto=compress,format",
   },
   {
     name: "Aditi Pandey",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Devishi Mahajan",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/d7cff530-2105-4bb6-a9ec-b1a00b61d359_Devishi.jpg?auto=compress,format",
   },
   {
     name: "Sanee Bharadwaj",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Ailin Chen",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b01fbf66-b40d-4763-8896-c9a363bd7239_Ailin+Chen+-+Ailin+Clarice+Chen.jpeg?auto=compress,format",
   },
   {
     name: "Ilika Mahajan",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/de9b1551-4922-4a0b-baf9-4003a6f9cc7a_Ilika+Mahajan_.jpg?auto=compress,format",
   },
   {
     name: "Shivam Shandilya",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/c233176a-0adf-4625-a462-f4448632ed95_SHIVAM+SHANDILYA.jpg?auto=compress,format",
   },
   {
     name: "Ayonija Katyan",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/a65e7c38-3355-4bfa-9fd9-bda597a82064_Ayonija_.jpg?auto=compress,format",
   },
   {
     name: "Mahi Tomar",
     position: "",
     team: "ccsocialmedia",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/9af74a62-618e-47f8-8967-a0b0313405eb_Mahi+Tomar.jpg?auto=compress,format",
   },
   {
     name: "Aditi Sharma",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/3369caf5-d116-4bd0-8a0b-d21942db72a6_Aditi+Sharma.jpg?auto=compress,format",
   },
   {
     name: "Khushi Bansal",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/12171385-d23b-4518-bc4b-af009722f3c9_Khushi+Bansal.jpeg?auto=compress,format",
   },
   {
     name: "Satvika Arora",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/7e0a4335-6a67-4834-9a1f-6c30fdabce76_Satvika+Arora.jpg?auto=compress,format",
   },
   {
     name: "Ananta Taneja",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/6a200f2e-3dd1-4e0a-aca5-66b7967cdae2_Ananta+Taneja_.jpg?auto=compress,format",
   },
   {
     name: "Lakshita Agarwal",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/951b0346-0f58-435a-bdc4-7749a6d8b31e_Lakshita+Agrawal.jpg?auto=compress,format",
   },
   {
     name: "Shashwat Singh",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/112b655b-0724-436b-a5d4-abd37bea2e05_Shashwat+Singh.jpg?auto=compress,format",
   },
   {
     name: "Devyansh Mishra",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Mannan Arora",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/ca2e4dfa-4a03-48fd-bc25-472a54713b54_C7348F72-8CD3-45A0-97C3-734522412317+-+Mannan+Arora.JPG?auto=compress,format",
   },
   {
     name: "Shrishti Krishna",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/8a647216-f4e2-4258-9879-5d90ed10fd0c_SHRISTI+KRISHNA.jpg?auto=compress,format",
   },
   {
     name: "Harshneet Khanna",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/545b0a30-37bb-4865-bc31-259155b64788_Harshneet+Khanna.png?auto=compress,format",
   },
   {
     name: "Monil Shah",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/75785e71-122b-47f2-9f72-dbb02bb8e318_Monil+shah.jpg?auto=compress,format",
   },
   {
     name: "Tanish Kesarwani",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
   },
   {
     name: "Ishika Jain",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/ee2d86f2-60fd-45b1-a200-11000d3d368e_Ishika+Jain.jpeg?auto=compress,format",
   },
   {
     name: "Oorja Sharma",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/0bd21586-cb3c-45f0-8ada-635a98c9e2d8_Oorja+Sharma_.jpg?auto=compress,format",
   },
   {
     name: "Vasudha Shrivastva",
     position: "",
     team: "CCsponsorship",
     behance:"",
     github:"",
     linkedin:"",
     instagram:"",
     image:
       "https://images.prismic.io/ieeemuj/b3bac313-7b07-4420-a6f6-a66fdcf28553_IMG_3523+-+Vasudha+Shrivastava.jpg?auto=compress,format",
   },

 ];

export default members;